/**
 * Initialize data
 */
export const LOAD_INIT_DATA_SUCCESS = 'LOAD_INIT_DATA_SUCCESS';
export const LOAD_INIT_DATA_FAILURE = 'LOAD_INIT_DATA_FAILURE';

/**
 * Projection loading for the instance view
 */
export const LOAD_PROJECTION_DATA_SUCCESS = 'LOAD_PROJECTION_DATA_SUCCESS';
export const LOAD_PROJECTION_DATA_FAILURE = 'LOAD_PROJECTION_DATA_FAILURE';

/**
 * Instance View interactions
 */
export const CHANGE_HIGHLIGHTED_INSTANCE = 'CHANGE_HIGHLIGHTED_INSTANCE';
// export const CHANGE_INSTANCE_VIEW_CLASSES = 'CHANGE_INSTANCE_VIEW_CLASSES';

/**
 * Matrix View interactions
 */
export const CHANGE_SELECTED_CLASS_IN_MATRIX_VIEW = 'CHANGE_SELECTED_CLASS_IN_MATRIX_VIEW';
export const CHANGE_SELECTED_LAYERS_IN_MATRIX_VIEW = 'CHANGE_SELECTED_LAYERS_IN_MATRIX_VIEW';
export const CHANGE_SELECTED_CLASS_AND_LOAD_EDGE_STAT_IN_MATRIX_VIEW_SUCCESS = 'CHANGE_SELECTED_CLASS_AND_LOAD_EDGE_STAT_IN_MATRIX_VIEW_SUCCESS';
export const CHANGE_SELECTED_CLASS_AND_LOAD_EDGE_STAT_IN_MATRIX_VIEW_FAILURE = 'CHANGE_SELECTED_CLASS_AND_LOAD_EDGE_STAT_IN_MATRIX_VIEW_FAILURE';
export const CHANGE_SELECTED_MATRIX_CELL = 'CHANGE_SELECTED_MATRIX_CELL';
export const CHANGE_SELECTED_NEURON = 'CHANGE_SELECTED_NEURON';

/**
 * Feature View
 */
export const INIT_FEATURE_IMPORTANCE_SUCCESS = 'INIT_FEATURE_IMPORTANCE_SUCCESS';
export const INIT_FEATURE_IMPORTANCE_FAILURE = 'INIT_FEATURE_IMPORTANCE_FAILURE';
export const LOAD_FEATURE_PROJECTION_SUCCESS = 'LOAD_FEATURE_PROJECTION_SUCCESS';
export const LOAD_FEATURE_PROJECTION_FAILURE = 'LOAD_FEATURE_PROJECTION_FAILURE';
export const CHANGE_BEST_ALL_OR_WORST_ALL = 'CHANGE_BEST_ALL_OR_WORST_ALL';
export const CHANGE_FEATURE_MODEL_TYPE = 'CHANGE_FEATURE_MODEL_TYPE';
export const CHANGE_TOGGLED_FEATURES = 'CHANGE_TOGGLED_FEATURES';